# Generated by Django 6.0.3 on 2026-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='shipping_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
